// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file admin/admin.proto (package admin, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin/admin.proto.
 */
export const file_admin_admin: GenFile = /*@__PURE__*/
  fileDesc("ChFhZG1pbi9hZG1pbi5wcm90bxIFYWRtaW4iGQoLVGVzdFJlcXVlc3QSCgoCb2sYASABKAgiMgoMVGVzdFJlc3BvbnNlEiIKCXRlc3RfZW51bRgBIAEoDjIPLmFkbWluLlRlc3RFbnVtKjcKCFRlc3RFbnVtEhkKFVRFU1RfRU5VTV9VTlNQRUNJRklFRBAAEhAKDFRFU1RfRU5VTV9PSxABMlQKC1Rlc3RTZXJ2aWNlEkUKBFRlc3QSEi5hZG1pbi5UZXN0UmVxdWVzdBoTLmFkbWluLlRlc3RSZXNwb25zZSIUgtPkkwIOOgEqIgkvYXBpL3Rlc3RCRFpCZ2l0aHViLmNvbS9hZ2VudC1zYXBpZW50L2ltbWlncmF0aW9uLWNoYXQtYWRtaW4taWRsLWdvL3Byb3RvL2FkbWluYgZwcm90bzM", [file_google_api_annotations]);

/**
 * @generated from message admin.TestRequest
 */
export type TestRequest = Message<"admin.TestRequest"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * Describes the message admin.TestRequest.
 * Use `create(TestRequestSchema)` to create a new message.
 */
export const TestRequestSchema: GenMessage<TestRequest> = /*@__PURE__*/
  messageDesc(file_admin_admin, 0);

/**
 * @generated from message admin.TestResponse
 */
export type TestResponse = Message<"admin.TestResponse"> & {
  /**
   * @generated from field: admin.TestEnum test_enum = 1;
   */
  testEnum: TestEnum;
};

/**
 * Describes the message admin.TestResponse.
 * Use `create(TestResponseSchema)` to create a new message.
 */
export const TestResponseSchema: GenMessage<TestResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin, 1);

/**
 * @generated from enum admin.TestEnum
 */
export enum TestEnum {
  /**
   * @generated from enum value: TEST_ENUM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TEST_ENUM_OK = 1;
   */
  OK = 1,
}

/**
 * Describes the enum admin.TestEnum.
 */
export const TestEnumSchema: GenEnum<TestEnum> = /*@__PURE__*/
  enumDesc(file_admin_admin, 0);

/**
 * @generated from service admin.TestService
 */
export const TestService: GenService<{
  /**
   * Test
   *
   * @generated from rpc admin.TestService.Test
   */
  test: {
    methodKind: "unary";
    input: typeof TestRequestSchema;
    output: typeof TestResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admin_admin, 0);

