// =============================================================================
// 后台管理接口 - 通用消息定义
// =============================================================================
//
// 版本: v1.0
// 更新时间: 2026-02-05
// 用途: gRPC 后台管理接口的通用消息类型
//
// 本文件定义了所有 Admin 服务共用的基础消息类型：
// - ApiResponse: 通用 API 响应（用于无额外数据返回的操作）
// - Pagination: 分页请求参数
// - PageInfo: 分页响应信息
// - TimeRange: 时间范围筛选
// - Empty: 空消息
//
// =============================================================================

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file admin/admin_common.proto (package admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin/admin_common.proto.
 */
export const file_admin_admin_common: GenFile = /*@__PURE__*/
  fileDesc("ChhhZG1pbi9hZG1pbl9jb21tb24ucHJvdG8SBWFkbWluIiwKC0FwaVJlc3BvbnNlEgwKBGNvZGUYASABKAUSDwoHbWVzc2FnZRgCIAEoCSItCgpQYWdpbmF0aW9uEgwKBHBhZ2UYASABKAUSEQoJcGFnZV9zaXplGAIgASgFIjoKCFBhZ2VJbmZvEg0KBXRvdGFsGAEgASgFEgwKBHBhZ2UYAiABKAUSEQoJcGFnZV9zaXplGAMgASgFIicKCVRpbWVSYW5nZRINCgVzdGFydBgBIAEoAxILCgNlbmQYAiABKAMiBwoFRW1wdHlCRFpCZ2l0aHViLmNvbS9hZ2VudC1zYXBpZW50L2ltbWlncmF0aW9uLWNoYXQtYWRtaW4taWRsLWdvL3Byb3RvL2FkbWluYgZwcm90bzM");

/**
 * ApiResponse - 通用 API 响应
 *
 * 用于不需要返回额外业务数据的操作（如：激活用户、封禁用户等）
 * 调用方应首先检查 code 字段判断操作是否成功
 *
 * 示例响应：
 * - 成功: { code: 0, message: "激活成功" }
 * - 失败: { code: 404, message: "用户不存在" }
 * - 参数错误: { code: 400, message: "reason 参数必填" }
 * - 认证失败: { code: 401, message: "缺少管理员身份信息 (x-admin-id)" }
 * - 服务器错误: { code: 500, message: "内部错误: ..." }
 *
 * @generated from message admin.ApiResponse
 */
export type ApiResponse = Message<"admin.ApiResponse"> & {
  /**
   * 业务状态码
   * - 0: 成功
   * - 400: 参数错误（如缺少必填字段、参数值无效）
   * - 401: 认证失败（如缺少 x-admin-id）
   * - 404: 资源不存在（如用户不存在、邀请码不存在）
   * - 500: 服务器内部错误
   *
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * 响应消息（中文）
   * 成功时返回操作结果描述，失败时返回错误原因
   *
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message admin.ApiResponse.
 * Use `create(ApiResponseSchema)` to create a new message.
 */
export const ApiResponseSchema: GenMessage<ApiResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin_common, 0);

/**
 * Pagination - 分页请求参数
 *
 * 用于列表查询请求中指定分页参数
 * 如不传递，默认 page=1, page_size=20
 *
 * @generated from message admin.Pagination
 */
export type Pagination = Message<"admin.Pagination"> & {
  /**
   * 页码，从 1 开始
   * 默认值: 1
   * 最小值: 1
   *
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * 每页数量
   * 默认值: 20
   * 最小值: 1
   * 最大值: 100
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;
};

/**
 * Describes the message admin.Pagination.
 * Use `create(PaginationSchema)` to create a new message.
 */
export const PaginationSchema: GenMessage<Pagination> = /*@__PURE__*/
  messageDesc(file_admin_admin_common, 1);

/**
 * PageInfo - 分页响应信息
 *
 * 用于列表查询响应中返回分页状态
 * 调用方可据此计算总页数: total_pages = ceil(total / page_size)
 *
 * @generated from message admin.PageInfo
 */
export type PageInfo = Message<"admin.PageInfo"> & {
  /**
   * 符合查询条件的总记录数
   *
   * @generated from field: int32 total = 1;
   */
  total: number;

  /**
   * 当前页码（与请求参数一致）
   *
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   * 每页数量（与请求参数一致）
   *
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;
};

/**
 * Describes the message admin.PageInfo.
 * Use `create(PageInfoSchema)` to create a new message.
 */
export const PageInfoSchema: GenMessage<PageInfo> = /*@__PURE__*/
  messageDesc(file_admin_admin_common, 2);

/**
 * TimeRange - 时间范围筛选
 *
 * 用于按时间范围筛选数据（如注册时间、激活时间）
 * 时间戳为 Unix 时间戳（秒），UTC 时区
 *
 * 注意：
 * - start 和 end 均为可选，可只传其一实现"之后"或"之前"筛选
 * - 边界包含：start <= time <= end
 * - 如 start > end，将返回空结果
 *
 * 示例：
 * - 查询 2026-01-01 至 2026-01-31 的数据:
 *   { start: 1735689600, end: 1738367999 }
 * - 查询 2026-01-01 之后的数据:
 *   { start: 1735689600 }
 *
 * @generated from message admin.TimeRange
 */
export type TimeRange = Message<"admin.TimeRange"> & {
  /**
   * 开始时间戳（秒，UTC）
   * 包含边界：time >= start
   *
   * @generated from field: int64 start = 1;
   */
  start: bigint;

  /**
   * 结束时间戳（秒，UTC）
   * 包含边界：time <= end
   *
   * @generated from field: int64 end = 2;
   */
  end: bigint;
};

/**
 * Describes the message admin.TimeRange.
 * Use `create(TimeRangeSchema)` to create a new message.
 */
export const TimeRangeSchema: GenMessage<TimeRange> = /*@__PURE__*/
  messageDesc(file_admin_admin_common, 3);

/**
 * Empty - 空消息
 *
 * 用于无参数或无返回值的 RPC 方法（如：健康检查）
 *
 * @generated from message admin.Empty
 */
export type Empty = Message<"admin.Empty"> & {
};

/**
 * Describes the message admin.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_admin_admin_common, 4);

